---
# tasks file for mattermost

- include_tasks: setup.yml

- include_tasks: update-code.yml

- include_tasks: symlink-shared.yml

- include_tasks: symlink.yml

- include_tasks: cleanup.yml
