---
- name: Mattermost | Create a symbolic link for datas
  ansible.builtin.file:
    src: "{{  item.value }}"
    dest: "{{ mattermost_install_dir }}/mattermost-{{ version }}/{{ item.key }}"
    owner: root
    group: root
    state: link
  loop: "{{ mattermost_shared_dirs | dict2items }}"

- name: Mattermost | Create symbolic links for client data
  ansible.builtin.file:
    src: "{{  item.value }}"
    dest: "{{ mattermost_install_dir }}/mattermost-{{ version }}/client/{{ item.key }}"
    owner: root
    group: root
    state: link
  loop: "{{ mattermost_client_shared_dirs | dict2items }}"
